### ISSUE TITLE
blog permalinks

### ISSUE THREAD

**Issue by shiffman** [shiffman/shiffman.net#30]
`2011/04/26/opencv-matching-faces-over-time.html`

should be:

`2011/04/26/opencv-matching-faces-over-time/`

**Comment by shiffman** [comment]
Also, just noticed there is "general" in the url, perhaps for the "general" category?  This should be removed I think?

http://shiffman.net/general/2011/04/26/opencv-matching-faces-over-time.html

becomes:

http://shiffman.net/2011/04/26/opencv-matching-faces-over-time/

?

**Comment by scottwooden** [comment]
Donezo

**Comment by shiffman** [comment]
Still seeing "general" in the URL.  Is there a way to remove that?  I can look into it.

http://shiffman.net/general/2011/04/26/opencv-matching-faces-over-time/

**Comment by scottwooden** [comment]
Think this is fixed? Can't see general now?
