### ISSUE TITLE
email signup visibility

### ISSUE THREAD

**Issue by shiffman** [shiffman/shiffman.net#32]
Wondering if there's a way to make the sign up for notifications more noticeable?  I don't think the top is the right place, but as of now you have to scroll all the way down to see it on the homepage.  Maybe fewer recent videos?  Or other ideas?

**Comment by scottwooden** [comment]
I've updated this, take have a look. Think it deserves it's own feature on the right? Let me know!

**Comment by shiffman** [comment]
This is great thank you!    Do you think a little "subscribe on youtube" button might work as well in that highlighted box?

**Comment by scottwooden** [comment]
Yep makes sense, I've added that in the blue video box
