### ISSUE TITLE
Specify playlists for video page

### ISSUE THREAD

**Issue by shiffman** [shiffman/shiffman.net#33]
How about a JSON file `playlists.json` where I put the playlist ids? Or I can just manually enter them in the JS itself.  Something like . . ?

```json
{
   "playlists":[
      "PLRqwX-V7Uu6atTSxoRiVnSuOn6JHnq2yV",
      "PLRqwX-V7Uu6ZmA-d3D0iFIvgrB5_7kB8H"
   ]
}
```

**Comment by scottwooden** [comment]
Yeah all I need is an array of playlist ID's and it can easily be slotted in :)

**Comment by scottwooden** [comment]
Do you have specific playlists in mind you want to pop in?

**Comment by shiffman** [comment]
How about to start:

```
PLRqwX-V7Uu6Zy51Q-x9tMWIv9cueOFTFA
PLRqwX-V7Uu6bI1SlcCRfLH79HZrFAtBvX
PLRqwX-V7Uu6a-SQiI4RtIwuOrLJGnel0r
PLRqwX-V7Uu6ZMlWHdcy8hAGDy6IaoxUKf
PLRqwX-V7Uu6atTSxoRiVnSuOn6JHnq2yV
PLRqwX-V7Uu6YVljJvFRCyRM6mmF5wMPeE
```

If you put these somewhere in the site's code, I can adjust from there.

**Comment by scottwooden** [comment]
I've added those videos into shiffman.net :)

**Comment by shiffman** [comment]
Awesome, looks great!
