### ISSUE TITLE
Learning and Books page (image for each entry?)

### ISSUE THREAD

**Issue by shiffman** [shiffman/shiffman.net#35]
I have redone the content a bit for the learning and books page.

http://shiffman.net/learning/
http://shiffman.net/books/

There are only two things on the learning page, but I'm planning on adding more.  Both of these pages now feel very text heavy.  Maybe each entry should have an image associated with it?  If you put in a placeholder with some dimensions I can make something for each one.

Also, for "Programming from A to Z" I might like to include two links, one for Java tutorials and one for JavaScript tutorials (see the dummy second link currently on the page).  Not sure how the design should / needs to be adjusted to accommodate this.

**Comment by scottwooden** [comment]
I'm going to mock up a page which can contain a list of links, which then can be clicked through to a blog type page. Would the work for the A - Z Programming list?

**Comment by shiffman** [comment]
Yes, that sounds good!

**Comment by scottwooden** [comment]
Also, for the learning page.. Let me know what images you want to accompany those sections, and I'll add them in. Images would be really nice I think

**Comment by shiffman** [comment]
I added some images to this page.  Let me know what you think, the could be cropped more perhaps to take up less vertical space and/or have a consistent height?   

http://shiffman.net/learning/

**Comment by scottwooden** [comment]
Images look good! I think it's a nice height?
