### ISSUE TITLE
bring in tutorials from A to Z course site?

### ISSUE THREAD

**Issue by shiffman** [shiffman/shiffman.net#36]
@scottwooden do you have any clever ideas as to how I might just bring over all these tutorials and just include them under "learning" on shiffman.net itself?

http://shiffman.github.io/A2Z-F15/
https://github.com/shiffman/A2Z-F15

**Comment by scottwooden** [comment]
Okay I've added 2 new pages which are:

/a2z/  : Which holds the course root of links etc.
/a2z-post/   : Which would hold the actual content

I guess you'd need to create posts from these so we can start populating those tempaltes?

**Comment by shiffman** [comment]
Awesome, these look great!  I think I can handle adding in all the content from here and will let you know if I have questions.

**Comment by shiffman** [comment]
This issue is no longer relevant, closing!
