### ISSUE TITLE
embed youtube videos on kinect page

### ISSUE THREAD

**Issue by shiffman** [shiffman/shiffman.net#38]
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZMlWHdcy8hAGDy6IaoxUKf

http://shiffman.net/p5/kinect/

**Comment by masterchop** [comment]
I manage to install openkinect into my Ubuntu machine but processing fails:

not compatible with the current OS or is a 32 bit system
UnsatisfiedLinkError: org.openkinect.freenect2.Device.jniInit()J
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.

**Comment by shiffman** [comment]
Videos are there now.
