### ISSUE TITLE
Overflow-x on homepage

### ISSUE THREAD

**Issue by Danzibob** [shiffman/shiffman.net#39]
![image](https://cloud.githubusercontent.com/assets/19689781/17926720/2db4a168-69ea-11e6-84c5-9f6e91557d16.png)
The rainbow image causes an overflow in the `right-container`. This can be solved by adding the `overflow-x: hidden;` property to the `right-container`

**Comment by shiffman** [comment]
I added it here https://github.com/shiffman/shiffman.net/commit/f257f64f49ec5e854daacd8623ebfdab0e7c52e9 but am still seeing the scroll. Any ideas?

**Comment by Danzibob** [comment]
The property appears to be being overwritten by the css on [this page (http://shiffman.net/css/main.css)](http://shiffman.net/css/main.css) line 113. Add the `overflow-x: hidden;` after the `overflow: scroll;` on that page and it should then work

**Comment by shiffman** [comment]
@scottwooden did I break something at some point?  Can you advise on how I should fix this if you have a spare minute?

**Comment by DexterShepherd** [comment]
@shiffman it looks like `overflow-x` is set to `hidden` on line 74 _layout.scss, but then reset `overflow: scroll` on line 570 of the same file. It doesn't seem like the `overflow: scroll` is needed anywhere so you should be able to delete line 570 and things will work again :)

**Comment by shiffman** [comment]
thank you!!! Fixed!
