### ISSUE TITLE
missing tokens1.png and tokens1.png images on twitter bot page

### ISSUE THREAD

**Issue by arsenijesavic** [shiffman/shiffman.net#41]
@shiffman  In the folder [a2z images](https://github.com/shiffman/shiffman.net/tree/gh-pages/a2z/images) you are missing two image files **tokens1.png** & **tokens2.png**, I think that's why they don't work on [twitter bots page](http://shiffman.net/a2z/twitter-bots/) ?

**Comment by shiffman** [comment]
Thanks, this is fixed now!
