### ISSUE TITLE
"CameraParams" does not exist

### ISSUE THREAD

**Issue by lorkel** [shiffman/shiffman.net#44]
I just started working with Kinect on Mac OS X and was able to get it up and running very easily with your tutorials. I was trying to follow the Code for v2: Point Cloud tutorial and I'm getting the following error:

<img width="679" alt="screen shot 2016-11-14 at 5 50 35 pm" src="https://cloud.githubusercontent.com/assets/6165552/20290106/e16a65d8-aa92-11e6-9e57-4bc196f40495.png">

I was also going through the other tutorials after installing them from the Processing v3 > Add Libraries and I'm getting the following errors:

ColorPointCloud2: The function "vertexAttribPointer()" expects parameters like: "vertexAttribPointer(int, int, int, boolean, int, int)"

I'm getting similar errors on DepthPointCloud2 and DepthThreshold2. Am I missing a library or something? Thank you!

**Comment by shiffman** [comment]
Hmmmm, I'll try to take a look.  Can you file this at https://github.com/shiffman/OpenKinect-for-Processing/issues?  I think it may be an issue with the library examples.
