### ISSUE TITLE
YouTube URL broken

### ISSUE THREAD

**Issue by medakk** [shiffman/shiffman.net#45]
The link to your YouTube page in the "About" section seems to be broken. [https://www.youtube.com/shiffman](https://www.youtube.com/shiffman) leads to a broken page. [https://www.youtube.com/user/shiffman](https://www.youtube.com/user/shiffman) works fine though.  

Changing the URL in [this file](https://github.com/shiffman/shiffman.net/blob/705d641a78d124a3a0bb06603a46c52011905fba/about.html) should fix it.

**Comment by haideralipunjabi** [comment]
I think this issue can be closed as the link is working fine now :smile:
