### ISSUE TITLE
rss feed?

### ISSUE THREAD

**Issue by heyarne** [shiffman/shiffman.net#48]
Hey, I find your content very informative and entertaining, thanks a lot!

I'd love to be able to consume it via RSS, but neither is the `feed.xml` linked to in page's html document, nor is it up to date (last entry: 2014), is this a bug or is it intended?

**Comment by shiffman** [comment]
I'm not generating "blog"-style content anymore that an RSS feed would make sense. However, if there's a broken link on the site somewhere I should remove it. Is there one or can this be closed?

**Comment by heyarne** [comment]
As far as I can tell there is none, so you can just close this.

**Comment by heyarne** [comment]
Or, well, I can. :)
