### ISSUE TITLE
SimpleOpenNi

### ISSUE THREAD

**Issue by totovr** [shiffman/shiffman.net#52]
# KinectV1 and SimpleOpenni

Hello! I could setup this library of SimpleOpenni in Processing 3, is it possible to added in the IDE of Processing to download via "add library"?

      https://github.com/totovr/SimpleOpenni/tree/Processing_3.3.6

Thanks!

**Comment by shiffman** [comment]
(I realize this is years later, apologies!) Questions like this are best answered at https://discourse.processing.org!
