### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by tobiasvonarx** [shiffman/shiffman.net#55]
A suggestion to switch to HTTPS encryption, as every website running HTTP will be flagged as "not secure" by browsers in the coming months. 
![image](https://user-images.githubusercontent.com/29151620/41194155-8b2745ea-6c17-11e8-9a06-6fdc3b632e22.png)

![image](https://user-images.githubusercontent.com/29151620/41194171-bb476232-6c17-11e8-87ef-2dbe3f6f609c.png)

**Comment by shiffman** [comment]
Done! Thanks for the reminder!
