### ISSUE TITLE
Accessibility - 1.4.3 Contrast (Minimum): (Level AA)

### ISSUE THREAD

**Issue by phucduong86** [shiffman/shiffman.net#81]
Results for: (https://shiffman.net)
Findings: Element sources:
```
<span class="intro">Learn Creative Code</span>
<a href="https://www.patreon.com/codingtrain?ty=h" target="_blank" class="btn primary">BECOME A PATRON</a>
<p>Sign up for live stream notifications via e-mail</p>
<button type="submit" class="email-btn" name="subscribe">GET UPDATES</button>
<p>Videos on how to code</p>
<a href="http://thecodingtrain.com" target="_blank" class="primary">GO TO SITE</a>
<h1>LEARNING PROCESSING</h1>
<p>Creative Coding for the Total Beginner</p>
<a href="https://www.amazon.com/Learning-Processing-Second-Edition-Programming/dp/0123944430/ref=as_li_ss_tl?ie=UTF8&amp;linkCode=sl1&amp;tag=learniproces-20&amp;linkId=757eff7b49e61c381b17a43c7dec3eee" class="primary">GET THE BOOK</a>
```

Results for: (https://shiffman.net/books/)
Findings: All link texts and button texts.

Results for: (https://shiffman.net/videos/)
Findings: 
```
<a href="http://youtube.com/shiffman" target="_blank" class="btn primary">THE CODING TRAIN ON YOUTUBE</a>
<h5>QUICK LINKS</h5>
<span>SUPPORT ON PATREON</span>
```
Results for: (https://shiffman.net/learning/)
Findings: 
```
<a href="https://shiffman.net/a2z/" class="body-link primary">2016 course website</a>
<h5>COURSES</h5>
```

Results for: (https://shiffman.net/about/)
Findings:
```
 <h5>QUICK LINKS</h5>
```

Results for: (https://shiffman.net/a2z/)
Findings:
 All link texts
```
<h5>Tutorials</h5>
```

Results for: (https://shiffman.net/a2z/closures/)
Texts of code with class="token function" on white background:
```
.token.function {
color: #DD4A68;
}
```

Results for: (https://shiffman.net/a2z/cfg/)
Findings: Texts of code with the following classes on white background:
```.token.selector, .token.attr-name, .token.string, .token.char, .token.builtin, .token.inserted {
color: #690;
}
```

**Comment by phucduong86** [comment]
@shiffman 
There are 2 accessible Prism themes for syntax highlighting. Can you take a look and see which one would you like to implement? 
https://github.com/ericwbailey/a11y-syntax-highlighting
Light theme: mostly AA and a few AAA level contrast level. A little hard to differenciate with the content's text color.
![image](https://user-images.githubusercontent.com/21692768/55369524-e8594b00-54c4-11e9-8efe-373cfdd36185.png)

Dark theme: AAA contrast level and in my opinion much easier to separate from text content.
![image](https://user-images.githubusercontent.com/21692768/55369572-1a6aad00-54c5-11e9-9b30-eeef0c405e8b.png)

**Comment by phucduong86** [comment]
Current result of the color contrast test:

https://github.com/ericwbailey/a11y-syntax-highlighting
![image](https://user-images.githubusercontent.com/21692768/55369796-0bd0c580-54c6-11e9-85a9-a7c2f521a837.png)

**Comment by shiffman** [comment]
I like the dark theme @phucduong86!
